export const START_GAME = 'START_GAME'
export const DEPLOY_PACMAN = 'DEPLOY_PACMAN'
export const MOVE_UP = 'MOVE_UP'
export const MOVE_DOWN = 'MOVE_DOWN'
export const MOVE_LEFT = 'MOVE_LEFT'
export const MOVE_RIGHT = 'MOVE_RIGHT'